name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: cyberuni/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
      skip-playwright: true

  release:
    uses: cyberuni/.github/.github/workflows/pnpm-release-changeset-oidc.yml@main
    needs: code
    permissions:
      id-token: write
      contents: write
      pull-requests: write

  docgen:
    if: github.ref == 'refs/heads/main'
    uses: cyberuni/.github/.github/workflows/pnpm-docs.yml@main
    needs: release
    # It pushes the built docs to gh-pages with GITHUB_TOKEN.
    permissions:
      contents: write
